# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               "Dan's Summer of Code"
tagline:             'My progress over the summer'
description:         'During this summer I am going to rewrite the parser used in analyzing SQL queries. On this blog, I will post my progress and new interesting things that I learnt.'
url:                 http://dan.ungureanu.me
baseurl:             '/gsoc-2015'
paginate:            5

# About/contact
author:
  name:              Dan Ungureanu
  url:               https://dan.ungureanu.me
  email:             dan@ungureanu.me

# Custom vars
fork:                https://github.com/udan11/phpmyadmin
abstract:            https://www.google-melange.com/gsoc/project/details/google/gsoc2015/udan11/5639274879778816
proposal:            https://drive.google.com/file/d/0B-VJ3ClMYRHFQzZzbjdaZ2J5UE0/view?usp=sharing
